### ISSUE TITLE
config.xml shouldn't be in www/

### ISSUE THREAD

**Issue by sylvinus** [brianleroux/Cordova#10]
For projects also using www/ as a document root it is insecure

**Comment by brianleroux** [comment]
I'm open to looking at this but in what way is it insecure?

http://www.w3.org/TR/widgets/

**Comment by sylvinus** [comment]
ok sorry! wasn't aware that the config.xml path was hardcoded in the widgets spec. 

I had this reflex because I saw your mail in there and was bitten in the past with publicly available configuration files ;-)

I guess it _could_ be an issue if too much new stuff goes into config.xml but easily solvable with proper access control so I'll close this one!

thanks

**Comment by brianleroux** [comment]
Well, hold up, there is a very real possability the spec needs work. The config.xml does contain important info for the running context (feature element abuse could be real). There could be good reasons to lock it down. =)
