### ISSUE TITLE
after fresh install make create returns errors

### ISSUE THREAD

**Issue by zanedev** [brianleroux/Cordova#12]
After running cordova install per the instructions and trying make create I get the following errors:
# write out the source for each native platform
# careful, this is destructive!!!

./bin/util/validate-config
# ./bin/create/blackberry

./bin/create/android
uname: illegal option -- o
usage: uname [-amnprsv]
./bin/create/android: line 13: [: =: unary operator expected
uname: illegal option -- o
usage: uname [-amnprsv]
./bin/create/android: line 17: [: =: unary operator expected
./bin/create/android: line 28: android: command not found
./bin/create/android: line 31: android: command not found
./bin/create/android: line 45: ./tmp/android/src/com/phonegap/vanilla/PhoneGapVanilla.java: No such file or directory
find: ./tmp/android/src/com/phonegap/vanilla/PhoneGapVanilla.java: No such file or directory
find: ./tmp/android/src/com/phonegap/vanilla/PhoneGapVanilla.java: No such file or directory
Traceback (most recent call last):
  File "./bin/create/android-convert-config", line 7, in <module>
    manifest_xml = parse(manifest_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: './tmp/android/AndroidManifest.xml'
make: **\* [create] Error 1

Not sure how to troubleshoot this.

**Comment by zanedev** [comment]
Okay I was able to debug it further and almost got it all the way... 

1) uname problem, edit the bin/create/android script to not call uname -u, my mac doesnt like that option.
2) I had to put the android sdk tools path on my system PATH in addition to the cordova root folder.
3) I had to manually create a new environment variable called "PHONEGAPLIB" that has the path to my phonegap installation.
4) I had to install ios-sim program from github: https://github.com/Fingertips/ios-sim

I noticed that you need to run make emulate first before running make debug so the emulators are running before it tries to install the compiled project files.

I have the vanilla sample app installing on android and running fine but it is failing to run on my ios simulator with the message: [DEBUG] Session could not be started: Error Domain=DTiPhoneSimulatorErrorDomain Code=1 UserInfo=0x10011ffd0 "iOS Simulator failed to install the application.".  The App does appear to be installed after failing but when running it, it just crashes.  I tried deleting all the iphone simulator files in ~/Library/Application Support and relaunching the simulator in case something was corrupted from a previous simulator but that didn't help.  

So close!! does anybody have any idea how to get around this last error I am getting when trying to deploy the ios simulator version?

MacOSX: 10.6.8
XCODE: 4.0.2
PHONEGAP: 0.9.6

**Comment by orbitaloop** [comment]
I have the same pb, the simulator doesn't start with the same error. Don't know what to do.

By the way, thanks zonathen, your addtitionals steps were really helpful. Should be included by default in the ReadMe file.

For Android, I had to create an AVD named default (run android in the terminal,  then create a new Virtual Device named default).
I also did the steps on the following thread:
https://github.com/brianleroux/Cordova/issues/11
https://github.com/brianleroux/Cordova/issues/7

**Comment by zanedev** [comment]
Hi orbitaloop not a problem, glad it helped.  The default AVD is mentioned in the readme already btw.  So the last error with installing on the ios simulator appears to be pathing related as well.  I debugged it far enough to see that it is hard coding the older version of phonegap-0.9.6.js or similar and couldn't figure out where that filename/path is added to the shell scripts that the generated xcode project uses.  Try opening the xcode project under tmp and running it from there and you'll see the errors.

I ran out of time to keep troubleshooting this bc I needed to spend that velocity on the actual project I am working on rather than the tools but I wish there was an answer bc I am currently copying and pasting between my xcode project and my android project pain in the butt!

**Comment by orbitaloop** [comment]
Yes, indeed, when building the xcode project manualy with xCode, there are some error regarding the copy of the phonegap file:
cp: /Users/sam/Documents/PhoneGapLib/javascripts/phonegap.0.9.3.js: No such file or directory

But i am not sure if it's related to our error  "Error Domain=DTiPhoneSimulatorErrorDomain Code=1", so as you, I need to give up for now, because I need to make progress on my project.

Maybe @BrianLeroux can help us on that? I know that they are working hard on build.phonegap, but for me, this is very important to have an automatic way of installing the app in the simulator and I use phonegap with plugins, and build.phonegap doesn't provide that.
