### ISSUE TITLE
How to use with PhoneGap 1.1.0?

### ISSUE THREAD

**Issue by robert-stuttaford** [brianleroux/Cordova#14]
I've gotten horribly stuck trying to get Cordova working with PhoneGap 1.1.0. Cordova is expecting the PhoneGap library to have VERSION, phonegap.VERSION.js and phonegap.VERSION.min.js (paraphrased), and the files in the zip for 1.1.0 don't match this at all.

Is anyone successfully using Cordova with 1.1.0 (and Xcode 4.x) ?

**Comment by ktiedt** [comment]
Havent been able to use Cordova since OSX Lion was released, Cordova hasnt been updated since 0.9.6 or 1.0 so.. probably not
