### ISSUE TITLE
Is the project under active development?

### ISSUE THREAD

**Issue by samyakbhuta** [brianleroux/Cordova#16]
I find Cordova attempting to solve many of the problems faced by PG developers. Esp, when one is targeting multiple platforms. However, I see the last commit is 9 month old. Just wanted to check if the project is in active development ? I have gone through the roadmap.md file as well ! 

Also, If the project is not under development, what is more relevant, (a) or (b) ?
(a) The fact that it no more makes sense. This would basically mean, no other developer should also waste the time contributing.
(b) Simply for the want of time. This would mean, there is strong case for this project to exist in this world. Contribution is needed, now !

**Comment by brianleroux** [comment]
sorta --- we're in the process of porting this all over to the top level phonegap proj
